name: Generate Keystore

on:
  workflow_dispatch:
    inputs:
      alias:
        description: 'Key Alias'
        required: true
        default: 'upload'
      password:
        description: 'Keystore Password (min 6 chars)'
        required: true
        default: 'binot123'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore
        run: |
          keytool -genkey -v -keystore my-upload-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias ${{ github.event.inputs.alias }} -dname "CN=Binot, OU=App, O=DENSLnetion, L=Jakarta, S=Jakarta, C=ID" -storepass ${{ github.event.inputs.password }} -keypass ${{ github.event.inputs.password }}
          
      - name: Encode Keystore to Base64
        run: |
          base64 my-upload-key.jks > base64_keystore.txt
          echo "=== SALIN KODE BASE64 DI BAWAH INI ==="
          cat base64_keystore.txt
          echo "======================================"


